name: Automated tests

on:
  push

env:
  GRADLE_VERSION: 6.9.4

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "zulu"

      - name: Install Gradle
        run: |
          wget "https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip"
          unzip -d $HOME "gradle-${GRADLE_VERSION}-bin.zip"
          export PATH=$HOME/gradle-${GRADLE_VERSION}/bin:$PATH

      - name: Start Selenoid
        run: docker run -d --name selenoid -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock aerokube/selenoid:latest-release

      - name: Start Selenoid UI
        run: docker run -d --name selenoid-ui -p 8080:8080 aerokube/selenoid-ui:latest-release

      - name: Pull Chrome image for Selenoid
        run: docker pull selenoid/chrome:114.0

      - name: Run tests
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          KEY: ${{ secrets.KEY }}
          TOKEN: ${{ secrets.TOKEN }}
          URI: ${{ vars.URI }}
          REMOTE_DRIVER_URL: "http://localhost:8080"
        run: gradle clean test -DuserLogin=${USER_NAME} -DuserPassword=${USER_PASSWORD} -Dkey=${KEY} -Dtoken=${TOKEN} -Duri=${URI} -DremoteDriverUrl=${REMOTE_DRIVER_URL}/wd/hub/ -DvideoStorage=${REMOTE_DRIVER_URL}/video/

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        #id: allure-report
        with:
          allure_results: allure-results
          #gh_pages: gh-pages
          #allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: test

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action
