name: Automated tests

on:
  push

env:
  GRADLE_VERSION: 6.9.4

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "zulu"

      - name: Install Gradle
        run: |
          wget "https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip"
          unzip -d $HOME "gradle-${GRADLE_VERSION}-bin.zip"
          export PATH=$HOME/gradle-${GRADLE_VERSION}/bin:$PATH
      
      - name: Selenoid
        uses: Xotabu4/selenoid-github-action@v2
        with:
          selenoid-start-arguments: |
            --browsers 'chrome' --version 114.0

      - name: Run tests
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          KEY: ${{ secrets.KEY }}
          TOKEN: ${{ secrets.TOKEN }}
          URI: ${{ vars.URI }}
          REMOTE_DRIVER_URL: "http://localhost:4444"
        run: gradle clean test -DuserLogin=${USER_NAME} -DuserPassword=${USER_PASSWORD} -Dkey=${KEY} -Dtoken=${TOKEN} -Duri=${URI} -DremoteDriverUrl=${REMOTE_DRIVER_URL}/wd/hub -DvideoStorage=${REMOTE_DRIVER_URL}/video/

      - name: Copy History
        uses: actions/checkout@v2
        if: always()
        with:
          ref: gh-pages
          path: gh-pages
          
      - name: Build Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: build/allure-results
          allure_history: allure-history
          keep_reports: 20
          
      - name: Publish Report
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
