name: Automated tests

on:
  push

env:
  GRADLE_VERSION: 7.2

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
          with:
            java-version: 11

      - name: Install Gradle
        run: |
          wget "https://services.gradle.org/distributions/gradle-${env.GRADLE_VERSION}-bin.zip"
          unzip -d $HOME gradle-${env.GRADLE_VERSION}-bin.zip
          export PATH=$HOME/gradle-${env.GRADLE_VERSION}/bin:$PATH

      - name: Start Selenoid
        run: docker run -d --name selenoid -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock aerokube/selenoid:latest-release

      - name: Start Selenoid UI
        run: docker run -d --name selenoid-ui -p 8080:8080 aerokube/selenoid-ui:latest-release

      - name: Pull Chrome image for Selenoid
          run: docker pull selenoid/chrome:114.0

      - name: Build project
        run: ./gradlew build

      - name: Run tests
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          KEY: ${{ secrets.KEY }}
          TOKEN: ${{ secrets.TOKEN }}
          URI: ${{ secrets.URI }}
          REMOTE_DRIVER_URL: "http://localhost:8083"

        run: ./gradlew clean test -DuserLogin=${USER_NAME} -DuserPassword=${USER_PASSWORD} -Dkey=${KEY} -Dtoken=${TOKEN} -Duri=${URI} -DremoteDriverUrl=${REMOTE_DRIVER_URL}/wd/hub/ -DvideoStorage=${REMOTE_DRIVER_URL}/video/

      - name: Generate Allure report
        run: ./gradlew allureReport

      - name: Upload Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: build/reports/allure-report